import java.util.ArrayList;

public class Data {

    public static String plazmide = "TTGCGCCGGCGAAAACGAAAGGCTCAGTCGAAAGACTGGGCCTTTCGTTTTATCTGTTGT" +
            "TTGTCGGTGAACGCTCTCCTGAGTAGGACAAATCCGCCGGGAGCGGATTTGAACGTTGCG" +
            "AAGCAACGGCCCGGAGGGTGGCGGGCAGGACGCCCGCCATAAACTGCCAGGCATCAAATT" +
            "AAGCAGAAGGCCATCCTGACGGATGGCCTTTTTGAGATCAATTCTTAAATTGTGAGCGGA" +
            "TAACAATTTGAGCTCGGTACCTTTTCGCGCGCGTTTCCCTGCAGGTGGCGCGCCTGTAAT" +
            "ACGACTCACTATAGGGGAATTGTGAGCGGATAACAATTCCCCCTCTAGAAATAATTTTGT" +
            "TTAACATTTAAATCCAGAAGGAGATATAACTATGCGGGGTTCTCATCATCATCATCATCA" +
            "TGGTATGGCTAGCATGACTGGTGGACAGCAAATGGGTCGCTCCGGTGATGATGATGACAA" +
            "GCTGAAGATAGCAGCCTTCAACATCCGCACCTTTGGGGAGACCAAGATGTCCAATGCTAC" +
            "GCTCGCCAGCTACATTGTTCGGATCGTGCGTCGTTACGACATCGTCCTCATCCAGGAGGT" +
            "CAGAGACAGCCACCTGGTGGCTGTGGGGAAGCTCCTGGACTATCTCAACCAGGATGACCC" +
            "AAACACCTACCACTATGTGGTCAGTGAGCCGCTGGGCCGCAACAGCTACAAGGAGCGCTA" +
            "CCTCTTTCTGTTCAGACCCAACAAGGTGTCCGTGCTGGACACCTACCAGTACGACGACGG" +
            "CTGCGAGTCCTGCGGGAACGACAGCTTCAGCCGGGAGCCCGCTGTGGTCAAGTTCTCATC" +
            "CCACTCCACCAAGGTCAAGGAATTTGCCATTGTTGCCCTGCACTCGGCCCCATCGGACGC" +
            "AGTGGCTGAGATTAATTCTCTCTACGATGTCTACCTGGATGTCCAGCAGAAGTGGCACTT" +
            "GAACGATGTCATGTTGATGGGCGATTTCAATGCTGACTGCAGCTACGTGACCTCCTCGCA" +
            "GTGGTCATCCATCCGCCTGCGTACGAGCTCCACCTTCCAGTGGCTGATTCCTGACAGTGC" +
            "CGACACCACGGCTACGTCCACGAACTGCGCCTATGACAGGATCGTGGTCGCAGGGTCTCT" +
            "GCTCCAGAGTTCTGTGGTTCCTGGCTCGGCCGCTCCCTTTGACTTCCAAGCTGCATACGG" +
            "ACTGAGCAATGAGATGGCCCTGGCCATCAGTGACCATTACCCGGTGGAGGTGACGCTGAC" +
            "ATAAGGACTTCCCATCTCCGGTTTAAACAGGCCTGCATGCAGCGTAATCATGGTCATTAA" +
            "TTAACCTCCTGTGTGAAATTGTTATCCGCTCTGCGTTAGCAATTTAACTGTGATAAACTA" +
            "CCGCATTAAAGCTTATCGATGATAAGCTGTCAAACATGAGAAGGATCCTAGCATAACCCC" +
            "TTGGGGCCTCTAAACGGGTCTTGAGGGGTTTTTTGCGCCGGCGGACACCATCGAATGGCG" +
            "CAAAACCTTTCGCGGTATGGCATGATAGCGCCCGGAAGAGAGTCAATTCAGGGTGGTGAA" +
            "TGTGAAACCAGTAACGTTATACGATGTCGCAGAGTATGCCGGTGTCTCTTATCAGACCGT" +
            "TTCCCGCGTGGTGAACCAGGCCAGCCACGTTTCTGCGAAAACGCGGGAAAAAGTGGAAGC" +
            "GGCGATGGCGGAGCTGAATTACATTCCCAACCGCGTGGCACAACAACTGGCGGGCAAACA" +
            "GTCGTTGCTGATTGGCGTTGCCACCTCCAGTCTGGCCCTGCACGCGCCGTCGCAAATTGT" +
            "CGCGGCGATTAAATCTCGCGCCGATCAACTGGGTGCCAGCGTGGTGGTGTCGATGGTAGA" +
            "ACGAAGCGGCGTCGAAGCCTGTAAAGCGGCGGTGCACAATCTTCTCGCGCAACGCGTCAG" +
            "TGGGCTGATCATTAACTATCCGCTGGATGACCAGGATGCCATTGCTGTGGAAGCTGCCTG" +
            "CACTAATGTTCCGGCGTTATTTCTTGATGTCTCTGACCAGACACCCATCAACAGTATTAT" +
            "TTTCTCCCATGAAGACGGTACGCGACTGGGCGTGGAGCATCTGGTCGCATTGGGTCACCA" +
            "GCAAATCGCGCTGTTAGCGGGCCCATTAAGTTCTGTCTCGGCGCGTCTGCGTCTGGCTGG" +
            "CTGGCATAAATATCTCACTCGCAATCAAATTCAGCCGATAGCGGAACGGGAAGGCGACTG" +
            "GAGTGCCATGTCCGGTTTTCAACAAACCATGCAAATGCTGAATGAGGGCATCGTTCCCAC" +
            "TGCGATGCTGGTTGCCAACGATCAGATGGCGCTGGGCGCAATGCGCGCCATTACCGAGTC" +
            "CGGGCTGCGCGTTGGTGCGGATATCTCGGTAGTGGGATACGACGATACCGAAGACAGCTC" +
            "ATGTTATATCCCGCCGTTAACCACCATCAAACAGGATTTTCGCCTGCTGGGGCAAACCAG" +
            "CGTGGACCGCTTGCTGCAACTCTCTCAGGGCCAGGCGGTGAAGGGCAATCAGCTGTTGCC" +
            "CGTCTCACTGGTGAAAAGAAAAACCACCCTGGCGCCCAATACGCAAACCGCCTCTCCCCG" +
            "CGCGTTGGCCGATTCATTAATGCAGCTGGCACGACAGGTTTCCCGACTGGAAAGCGGGCA" +
            "GTAATTCCGGATCTGCATCGCAGGATGCTGCTGGCTACCCTGTGGAACACCTACATCTGT" +
            "ATTAACGAAGCGCTGGCATTGACCCTGAGTGATTTTTCTCTGGTCCCGCCGCATCCATAC" +
            "CGCCAGTTGTTTACCCTCACAACGTTCCAGTAACCGGGCATGTTCATCATCAGTAACCCG" +
            "TATCGTGAGCATCCTCTCTCGTTTCATCGGTATCATTACCCCCATGAACAGAAATCCCCC" +
            "TTACACGGAGGCATCAGTGACCAAACAGGAAAAAACCGCCCTTAACATGGCCCGCTTTAT" +
            "CAGAAGCCAGACATTAACGCTTCTGGAGAAACTCAACGAGCTGGACGCGGATGAACAGGC" +
            "AGACATCTGTGAATCGCTTCACGACCACGCTGATGAGCTTTACCGCAGCTGCCTCGCGCG" +
            "TTTCGGTGATGACGGTGAAAACCTCTGACACATGCAGCTCCCGGAGACGGTCACAGCTTG" +
            "TCTGTAAGCGGATGCCGGGAGCAGACAAGCCCGTCAGGGCGCGTCAGCGGGTGTTGGCGG" +
            "GTGTCGGGGCGCAGCCATGACCCAGTCACGTAGCGATAGCGGAGTGTATACTGGCTTAAC" +
            "TATGCGGCATCAGAGCAGATTGTACTGAGAGTGCACCATATGCGGTGTGAAATACCGCAC" +
            "AGATGCGTAAGGAGAAAATACCGCATCAGGCGCTCTTCCGCTTCCTCGCTCACTGACTCG" +
            "CTGCGCTCGGTCGTTCGGCTGCGGCGAGCGGTATCAGCTCACTCAAAGGCGGTAATACGG" +
            "TTATCCACAGAATCAGGGGATAACGCAGGAAAGAACATGTGAGCAAAAGGCCAGCAAAAG" +
            "GCCAGGAACCGTAAAAAGGCCGCGTTGCTGGCGTTTTTCCATAGGCTCCGCCCCCCTGAC" +
            "GAGCATCACAAAAATCGACGCTCAAGTCAGAGGTGGCGAAACCCGACAGGACTATAAAGA" +
            "TACCAGGCGTTTCCCCCTGGAAGCTCCCTCGTGCGCTCTCCTGTTCCGACCCTGCCGCTT" +
            "ACCGGATACCTGTCCGCCTTTCTCCCTTCGGGAAGCGTGGCGCTTTCTCATAGCTCACGC" +
            "TGTAGGTATCTCAGTTCGGTGTAGGTCGTTCGCTCCAAGCTGGGCTGTGTGCACGAACCC" +
            "CCCGTTCAGCCCGACCGCTGCGCCTTATCCGGTAACTATCGTCTTGAGTCCAACCCGGTA" +
            "AGACACGACTTATCGCCACTGGCAGCAGCCACTGGTAACAGGATTAGCAGAGCGAGGTAT" +
            "GTAGGCGGTGCTACAGAGTTCTTGAAGTGGTGGCCTAACTACGGCTACACTAGAAGGACA" +
            "GTATTTGGTATCTGCGCTCTGCTGAAGCCAGTTACCTTCGGAAAAAGAGTTGGTAGCTCT" +
            "TGATCCGGCAAACAAACCACCGCTGGTAGCGGTGGTTTTTTTGTTTGCAAGCAGCAGATT" +
            "ACGCGCAGAAAAAAAGGATCTCAAGAAGATCCTTTGATCTTTTCTACGGGGTCTGACGCT" +
            "CAGTGGAACGAAAACTCACGTTAAGGGATTTTGGTCATGAGATTATCAAAAAGGATCTTC" +
            "ACCTAGATCCTTTTAAATTAAAAATGAAGTTTTAAATCAATCTAAAGTATATATGAGTAA" +
            "ACTTGGTCTGACAGTTACCAATGCTTAATCAGTGAGGCACCTATCTCAGCGATCTGTCTA" +
            "TTTCGTTCATCCATAGTTGCCTGACTCCCCGTCGTGTAGATAACTACGATACGGGAGGGC" +
            "TTACCATCTGGCCCCAGTGCTGCAATGATACCGCGAGAACCACGCTCACCGGCTCCAGAT" +
            "TTATCAGCAATAAACCAGCCAGCCGGAAGGGCCGAGCGCAGAAGTGGTCCTGCAACTTTA" +
            "TCCGCCTCCATCCAGTCTATTAATTGTTGCCGGGAAGCTAGAGTAAGTAGTTCGCCAGTT" +
            "AATAGTTTGCGCAACGTTGTTGCCATTGCTGCAGGCATCGTGGTGTCACGCTCGTCGTTT" +
            "GGTATGGCTTCATTCAGCTCCGGTTCCCAACGATCAAGGCGAGTTACATGATCCCCCATG" +
            "TTGTGCAAAAAAGCGGTTAGCTCCTTCGGTCCTCCGATCGTTGTCAGAAGTAAGTTGGCC" +
            "GCAGTGTTATCACTCATGGTTATGGCAGCACTGCATAATTCTCTTACTGTCATGCCATCC" +
            "GTAAGATGCTTTTCTGTGACTGGTGAGTACTCAACCAAGTCATTCTGAGAATAGTGTATG" +
            "CGGCGACCGAGTTGCTCTTGCCCGGCGTCAACACGGGATAATACCGCGCCACATAGCAGA" +
            "ACTTTAAAAGTGCTCATCATTGGAAAACGTTCTTCGGGGCGAAAACTCTCAAGGATCTTA" +
            "CCGCTGTTGAGATCCAGTTCGATGTAACCCACTCGTGCACCCAACTGATCTTCAGCATCT" +
            "TTTACTTTCACCAGCGTTTCTGGGTGAGCAAAAACAGGAAGGCAAAATGCCGCAAAAAAG" +
            "GGAATAAGGGCGACACGGAAATGTTGAATACTCATACTCTTCCTTTTTCAATATTATTGA" +
            "AGCATTTATCAGGGTTATTGTCTCATGAGCGGATACATATTTGAATGTATTTAGAAAAAT" +
            "AAACAAATAGGGGTTCCGCGCACATTTCCCCGAAAAGTGCCACCTGACGTCTAAGAAACC" +
            "ATTATTATCATGACATTAACCTATAAAAATAGGCGTATCACGAGGCCCT";

    public static String plazmine_rev = new StringBuilder(plazmide).reverse().toString();

    public static String test = "ATGCGGGGTTCTCATCATCATCATCATCATGGTATGGCTAGCATGACTGGTGGACAGCAAATGGGTCGCT" +
            "CCGGTGATGATGATGACAAGCTGAAGATAGCAGCCTTCAACATCCGCACCTTTGGGGAGACCAAGATGTC" +
            "CAATGCTACGCTCGCCAGCTACATTGTTCGGATCGTGCGTCGTTACGACATCGTCCTCATCCAGGAGGTC" +
            "AGAGACAGCCACCTGGTGGCTGTGGGGAAGCTCCTGGACTATCTCAACCAGGATGACCCAAACACCTACC" +
            "ACTATGTGGTCAGTGAGCCGCTGGGCCGCAACAGCTACAAGGAGCGCTACCTCTTTCTGTTCAGACCCAA" +
            "CAAGGTGTCCGTGCTGGACACCTACCAGTACGACGACGGCTGCGAGTCCTGCGGGAACGACAGCTTCAGC" +
            "CGGGAGCCCGCTGTGGTCAAGTTCTCATCCCACTCCACCAAGGTCAAGGAATTTGCCATTGTTGCCCTGC" +
            "ACTCGGCCCCATCGGACGCAGTGGCTGAGATTAATTCTCTCTACGATGTCTACCTGGATGTCCAGCAGAA" +
            "GTGGCACTTGAACGATGTCATGTTGATGGGCGATTTCAATGCTGACTGCAGCTACGTGACCTCCTCGCAG" +
            "TGGTCATCCATCCGCCTGCGTACGAGCTCCACCTTCCAGTGGCTGATTCCTGACAGTGCCGACACCACGG" +
            "CTACGTCCACGAACTGCGCCTATGACAGGATCGTGGTCGCAGGGTCTCTGCTCCAGAGTTCTGTGGTTCC" +
            "TGGCTCGGCCGCTCCCTTTGACTTCCAAGCTGCATACGGACTGAGCAATGAGATGGCCCTGGCCATCAGT" +
            "GACCATTACCCGGTGGAGGTGACGCTGACATAA";

    public static String test_rev = new StringBuilder(test).reverse().toString();

    // Only used for reference, actually never called anywhere
    public static String[] codonTable1 = {"ATT", "ATC", "ATA",//I
            "CTT", "CTC", "CTA", "CTG", "TTA", "TTG",//L
            "GTT", "GTC", "GTA", "GTG",//V
            "TTT", "TTC",//F
            "ATG",//M
            "TGT", "TGC", //C
            "GCT", "GCC", "GCA", "GCG",//A
            "GGT", "GGC", "GGA", "GGG",//G
            "CCT", "CCC", "CCA", "CCG",//P
            "ACT", "ACC", "ACA", "ACG", //T
            "TCT", "TCC", "TCA", "TCG", "AGT", "AGC", //S
            "TAT", "TAC",//Y
            "TGG", //W
            "CAA", "CAG", //Q
            "AAT", "AAC", //N
            "CAT", "CAC", //H
            "GAA", "GAG", //E
            "GAT", "GAC", //D
            "AAA", "AAG", //K
            "CGT", "CGC", "CGA", "CGG", "AGA", "AGG", //R
            "TAA", "TAG", "TGA"};//STOP

    public static String[] codonTable2 = {"I", "L", "V", "F", "M", "C", "A", "G", "P", "T", "S", "Y", "W", "Q", "N", "H", "E", "D", "K", "R", "STOP"};
}
